default: &default
  adapter: postgresql
  encoding: unicode

development:
  adapter: postgresql
  database: library_api_development
  username: library_api_development
  password: library_api_development
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: library_api_test
  username: library_api_test
  password: library_api_test
  encoding: unicode
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_URL'] %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
